"""Initial migration1

Revision ID: 55de61b1654c
Revises: 
Create Date: 2025-03-26 00:47:59.522390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55de61b1654c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('cat')

    # ### end Alembic commands ###
